spring.application.name=masterSkewb
var1:valor definido no app.aproperties
spring.datasource.url=jdbc:mysql://localhost:3306/master_skewb?createDatabaseIfNotExist=TRUE
spring.datasource.username=
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update