spring.application.name=masterSkewb
spring.datasource.url=jdbc:mysql://localhost:3306/masterskewb?createDatabaseIfNotExist=TRUE
spring.datasource.username=root
spring.datasource.password=Mysql123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.locations=classpath:db/migration/mysql
spring.flyway.enabled=true